---
title: DASHBOARD
author: Hoang Quoc Cuong
date: last-modified
format:
  html:
    toc: true
    toc-title: "Mục lục"
    toc-expand: 3
    toc-depth: 6
    grid:
      sidebar-width: 250px
    toc-location: left
    number-sections: true
    number-depth: 8
    page-layout: full
    code-fold: true
    code-summary: "Show the code"
    embed-resources: true
    anchor-sections: true
    smooth-scroll: false
engine: knitr
knitr:
  opts_chunk:
    R.options:
      width: 140
editor_options: 
  chunk_output_type: console
---

```{r, echo=FALSE, results='hide'}
knitr::opts_chunk$set(message = FALSE,  
                      warning = FALSE
                      # echo = FALSE
                      # results = 'hide'
                      )   
```




```{r}
library(rmarkdown)
library(quarto)
library(gsheet)
library(dplyr)
library(readxl)
library(gsheet)

df_master <- gsheet2tbl(url ="https://docs.google.com/spreadsheets/d/15IX-1-M-OmmOb9doFghPan-DrN5yzpmNYiBE02Xrjgk/edit?gid=0#gid=0")

df_master <- as.data.frame(df_master)

df_master
```


```{r}
df_master <- df_master |> subset(YEAR >= 2025)

df_master
```


```{r}
if(Sys.info()['sysname'] == "Windows"){

setwd("F:/VAULT12/R/DRCUONG_PASTEUR/FINAL_SXH")
  
} else {

setwd("/home/rp1/Documents/canthosxh/")

}

CLEAN_DATA <- "CLEAN_DATA.qmd"
REPORT_ALL <- "www_gom_all_www.qmd"
REPORT_ALL_CREATED <- "REPORT_ALL_CREATED.qmd"

CLEAN_DATA_OUTPUT <- paste0("CLEAN_DATA_OUTPUT")

getwd()
```

```{r}
df_master$SHEET -> unique_sheet
unique_sheet <- unique(unique_sheet)
```


```{r}
saveRDS(CLEAN_DATA_OUTPUT, "CLEAN_DATA_OUTPUT.rds")

if (!file.exists(CLEAN_DATA_OUTPUT)){
   dir.create(file.path(CLEAN_DATA_OUTPUT))
} 
```


```{r}

# h <- 1
# i <- 2

repeat{
  
  
# library(foreach)
# library(doParallel)
# 
# # How many cores does your CPU have
# n_cores <- detectCores()
# n_cores
# cluster <- makeCluster(n_cores - 3)
# registerDoParallel(cluster)

  
  # OUTPUT RAW DATA
  
  for(h in 1:length(unique_sheet)){
  
  df_master_SXH <- df_master |> subset(SHEET == unique_sheet[h])
    
    for(i in 1:nrow(df_master_SXH)){
      
      df_master_SXH$LINK[i] -> SXH_url
      saveRDS(SXH_url, "SXH_url.rds")
      
      df_master_SXH$SHEET[i] -> SXH_sheet
      saveRDS(SXH_sheet, "SXH_sheet.rds")
      
      df_master_SXH$YEAR[i] -> SXH_year
      saveRDS(SXH_year, "SXH_year.rds")
      ### NOTE ###
      # CLEAN_DATA sẽ chuẩn lại tên TTYT KV dựa theo PHUONG_XA, vì vậy các năm 2024 trở về trước cần có danh sách chuẩn TTYT KV để khớp tên
      
      
      try(quarto:::quarto_render(CLEAN_DATA,
                                 output_format = "html",
                                 # NẾU MUỐN OUTPUT RA CUSTOM DIR THÌ PHẢI SET Ở YAML
                                 output_file = paste0(unique_sheet[h],
                                                      "_",
                                                      df_master_SXH$YEAR[i],
                                                      ".html")
                                 )
          )
      
     
    }
  }
    
    

  # OUTPUT REPORT ALL
  
  for(h in 1:length(unique_sheet)){
  
  df_master_SXH <- df_master |> subset(SHEET == unique_sheet[h])
    
    for(i in 1:nrow(df_master_SXH)){
      
      df_master_SXH$LINK[i] -> SXH_url
      saveRDS(SXH_url, "SXH_url.rds")
      
      df_master_SXH$SHEET[i] -> SXH_sheet
      saveRDS(SXH_sheet, "SXH_sheet.rds")
      
      df_master_SXH$YEAR[i] -> SXH_year
      saveRDS(SXH_year, "SXH_year.rds")
      
      
      
      
     try( quarto:::quarto_render(REPORT_ALL_CREATED,
                       output_format = "html"
                       # output_file = paste0("REPORT_CREATED",
                       #                      unique_sheet[h],
                       #                      "_",
                       #                      df_master_SXH$YEAR[i],
                       #                      ".html")
                                 )
     )
      
      
      
      
      try(quarto:::quarto_render(REPORT_ALL,
                       output_format = "html",
                       output_file = paste0("REPORT_",
                                            unique_sheet[h],
                                            "_",
                                            df_master_SXH$YEAR[i],
                                            ".html")
                                 )
          )
      
     
    }
  }
  
  
   try(quarto:::quarto_render("ALL_RAW.qmd",
                       output_format = "html"
                                 )
          )
  
    
# stopCluster(cl = cluster)
  Sys.sleep(3000)
  
}
```


```{r}
 # try(system('/home/rp1/Documents/autocommit.sh'))
```




```{r}
quarto:::quarto_render(REPORT_ALL_CREATED,
                       output_format = "html"
                       # output_file = paste0("REPORT_CREATED",
                       #                      unique_sheet[h],
                       #                      "_",
                       #                      df_master_SXH$YEAR[i],
                       #                      ".html")
                                 )


quarto:::quarto_render(REPORT_ALL,
                       output_format = "html",
                       output_file = paste0("REPORT_",
                                            unique_sheet[h],
                                            "_",
                                            df_master_SXH$YEAR[i],
                                            ".html")
                                 )
```





















