---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
CLEAN_DATA_OUTPUT <- readRDS("CLEAN_DATA_OUTPUT.rds")

SXH_year <- readRDS("SXH_year.rds")

file_loop <- list.files(path = paste0(CLEAN_DATA_OUTPUT, "/"),
                        pattern = "_YEAR_")

grep(SXH_year,
     file_loop,
     value = T) -> file_input

grep("\\.rds",
     file_input,
     value = T) -> file_input


SXH_sheet <- readRDS("SXH_sheet.rds")

name_file_input <- paste0(SXH_sheet, "_YEAR_", SXH_year, ".rds")

file_input[file_input %in% name_file_input] -> file_input_ok

gsub(pattern = "\\.rds", "", file_input_ok) -> title_chuan


title_part <- "---
title: BÁO CÁO CHI TIẾT"

sink(file = "REPORT_ALL_TITLE.qmd")
cat( paste(title_part, title_chuan),
    sep = "\n")
sink()


```

```{r}
# system2(command = "type",
#         args    = c("REPORT_ALL_TITLE.qmd" ,
#         "REPORT_ALL_CONTENT.qmd"),
#         stdout = "REPORT_ALL.qmd")

# shell(cmd = "type REPORT_ALL_TITLE.qmd REPORT_ALL_CONTENT.qmd > www_gom_all_www.qmd")
```

```{r}
system('/home/rp1/Documents/canthosxh/combine.sh')
```













